---
- name: Create .ssh directory for user foo and copy authorized_keys file
  hosts: centos
  remote_user: foo

  tasks:
  - name: Create ~/.ssh directory
    ansible.builtin.file:
      path: /home/foo/.ssh
      state: directory
      mode: '0700'

  - name: copy authorized_keys file
    ansible.builtin.copy:
      src: ./templates/authorized_keys
      dest: /home/foo/.ssh/authorized_keys
      mode: '0600'
